---
title: "Tis is the tittle"
author: "me"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

******************************************
* The following text is provided
* for easier cutting and pasting as you
* work through the exercises in
* Module 2 - lesson 2: R Markdown Syntax
******************************************

# This is a level 1 header

### This is a level 3 header

Here is a link to [GOOGLE](https://www.google.com/)

Here is a word in **bold** and another word in __bold__.

Here is a word in *italics* and another word in _italics_.

When we compile our document, we are using the `rmarkdown` package.

Here are some example R commands:

```
2+2
mean(c(1,2,3,4,5))
```


Here is an example of a non-numbered list:

* Breakfast
    - food
        + eggs
        + toast
        + bacon
    - drink
        + apple juice
* Lunch
    - taco
* Dinner
    - baked chicken
    - broccoli
    - rice


Here is an example of a numbered list:

1. Breakfast
    a. food
        i. eggs
        ii. toast
        iii. bacon
    b. drink
        i. apple juice
2. Lunch
    a. taco
3. Dinner
    a. baked chicken
    b. broccoli
    c. rice


Here is an example of a blockquote:

> This is a block quote. This
> paragraph has two lines.
>
> 1. This is a list inside a block quote.
> 2. Second item.


Here is an example of a nested blockquote:

> This is a block quote. This
> paragraph has two lines.
>
> > This text is nested


Here is an example of code in a blockquote:

>     2+2
>     mean(c(1,2,3,4,5))


